services:
  sentinel:
    container_name: sentinel
    image: yuanyuexiang/sentinel:v2
    restart: always
    environment:
      NEXT_PUBLIC_API_BASE_URL: "http://admin.192.168.86.30.nip.io"
      NEXT_PUBLIC_API_PREFIX: "/consultant/api"
    healthcheck:
      disable: true
    ports:
      - "3000:3000"
    networks:
      - matrix-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sentinel.rule=Host(`admin.10.140.208.14.nip.io`)"
      - "traefik.http.routers.sentinel.entrypoints=web"
      - "traefik.http.routers.sentinel.service=sentinel"
      - "traefik.http.services.sentinel.loadbalancer.server.port=3000"

networks:
  matrix-network:
    external: true
