services:
  sentinel:
    container_name: sentinel
    image: yuanyuexiang/sentinel:v2
    restart: always
    healthcheck:
      disable: true
    ports:
      - "3000:3000"
    networks:
      - matrix-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sentinel.rule=Host(`admin.10.140.208.14.nip.io`)"
      - "traefik.http.routers.sentinel.entrypoints=web"
      - "traefik.http.routers.sentinel.service=sentinel"
      - "traefik.http.services.sentinel.loadbalancer.server.port=3000"

networks:
  matrix-network:
    driver: bridge
    name: matrix-network
